version: '3'
services:
  activemq:
    container_name: activemq
    image: vromero/activemq-artemis
    ports:
      - "8161:8161"
      - "61616:61616"
  importer:
    build: importer/.
    ports:
      - "5050:5050"
    depends_on:
      - activemq
  aggregator:
     build: aggregator/.
     ports:
      - "5051:5051"
     depends_on:
      - activemq